### ISSUE TITLE
its have bug

### ISSUE THREAD

**Issue by lordmen99** [tn710617/FacebookOptimizedLiveStreamSellingSystem#1]
i havetry localy with xampp, when try post /api/token

get error "{
    "result": false,
    "response": "The token is invalid"
}"

why show this?

**Comment by tn710617** [comment]
May I ask if you use the code from Frontend, or you carve the frontend on your own according to the document?

**Comment by lordmen99** [comment]
first, i build android app from link, its can login but stuck loading. then second use postmen with add paramter like in document. still invalid token.

**Comment by tn710617** [comment]
Dear loadmen, 
Since this project is maintained respectively by different ends. Currently there has been some update on Backend, and other end hasn't kept track of backend. 
You could either download backend service and customise the Android or open an issue on Android informing its maintainer.

**Comment by lordmen99** [comment]
ok, i see, i think problem from graph api in app laravel. btw, any live android app in playstore with this backend?

**Comment by tn710617** [comment]
I don't think so, since the token system was specifically customised for the other ends. If you are interested, the document of the backend is available. You could carve the Android end on your own.

**Comment by lordmen99** [comment]
i want ask about this :

Authorization: Bearer mNHuBWTW3fgB1PC0jUZ4A9jF5b2eckBqSyBAdkH3X31SJApZMWgZHjkVixK7

after bearer its token from app laravel or token facebook login?

**Comment by tn710617** [comment]
You will have to feed [Create New User](https://tn710617.github.io/API_Document/FacebookOptimizedSellingSystem/#%E5%85%B1%E5%90%8C-common-%E6%9B%B4%E6%96%B0%E6%88%96%E5%BB%BA%E7%AB%8B%E6%96%B0token-update-or-insert-a-new-token-post) API with token got from Facebook

**Comment by lordmen99** [comment]
ok, then?

**Comment by tn710617** [comment]
Sorry about that, but regarding usage instruction, you have to look closely to the document, I can't explain case by case.

**Comment by lordmen99** [comment]
ok, i will try make it working. actualy for create user with token still not working, POST /api/token

**Comment by lordmen99** [comment]
this issue in this app http://prntscr.com/n93wu2

**Comment by tn710617** [comment]
Please look closer to the document.
The backend will verify the token you provided with FB, and return a prolonged token along with expiry_time if the token is verified. 
I'm sorry, but I'm afraid I will not be able to reply the basic usage issue.
Kindly look closer to the document.
Many thanks!
